<?php
/**
 * Theme functions and definitions
 * 
 * Enqueues the React assets generated by Vite in the 'dist' folder.
 */

function spet_store_setup() {
    // Add default posts and comments RSS feed links to head.
    add_theme_support( 'automatic-feed-links' );

    // Let WordPress manage the document title.
    add_theme_support( 'title-tag' );

    // Enable support for Post Thumbnails on posts and pages.
    add_theme_support( 'post-thumbnails' );
}
add_action( 'after_setup_theme', 'spet_store_setup' );

function spet_store_enqueue_scripts() {
    $theme_dir = get_template_directory();
    $theme_uri = get_template_directory_uri();
    
    // Check for the Vite manifest file generated during the build process
    $manifest_path = $theme_dir . '/dist/.vite/manifest.json';
    
    if (file_exists($manifest_path)) {
        $manifest = json_decode(file_get_contents($manifest_path), true);
        
        // Find the entry point (index.html) in the manifest
        if (isset($manifest['index.html'])) {
            $entry = $manifest['index.html'];
            
            // Enqueue generated CSS files
            if (isset($entry['css'])) {
                foreach ($entry['css'] as $index => $css_file) {
                    wp_enqueue_style(
                        'spet-store-style-' . $index, 
                        $theme_uri . '/dist/' . $css_file, 
                        array(), 
                        null
                    );
                }
            }
            
            // Enqueue generated JavaScript file
            if (isset($entry['file'])) {
                wp_enqueue_script(
                    'spet-store-script', 
                    $theme_uri . '/dist/' . $entry['file'], 
                    array(), 
                    null, 
                    true // Load in footer
                );
                
                // We need to add type="module" to the React script because Vite builds ES modules
                add_filter('script_loader_tag', function($tag, $handle, $src) {
                    if ('spet-store-script' === $handle) {
                        return '<script type="module" src="' . esc_url($src) . '"></script>';
                    }
                    return $tag;
                }, 10, 3);
            }
        }
    } else {
        // If manifest doesn't exist, log an admin notice
        if (is_user_logged_in() && current_user_can('manage_options')) {
            error_log('Vite manifest not found. Please run "npm run build" in the theme directory.');
        }
    }
}
add_action( 'wp_enqueue_scripts', 'spet_store_enqueue_scripts' );
